apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jira-timesheet-sync
  annotations:
    # Adjust for your ingress controller
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: jira-timesheet-sync.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jira-timesheet-sync
                port:
                  name: http
  tls:
    - hosts:
        - jira-timesheet-sync.example.com
      secretName: jira-timesheet-sync-tls
